# Generated by Django 6.1.1 on 2026-09-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nhóm độ tuổi')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Đặc điểm đọc')),
                ('badge_color', models.CharField(default='bg-blue-100 text-blue-800', help_text='Class CSS Tailwind', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nhóm tuổi',
                'verbose_name_plural': 'Nhóm tuổi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tình trạng')),
                ('rating_percentage', models.PositiveIntegerField(default=90, verbose_name='Độ mới (%)')),
                ('badge_color', models.CharField(default='bg-emerald-100 text-emerald-800', max_length=50)),
                ('criteria', models.CharField(blank=True, help_text='Vd: Gáy nguyên vẹn, ruột sách sạch tinh, không quăn gập mép', max_length=255, verbose_name='Tiêu chuẩn đánh giá')),
            ],
            options={
                'verbose_name': 'Tình trạng sách cũ',
                'verbose_name_plural': 'Tình trạng sách cũ',
                'ordering': ['-rating_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên thể loại')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả thể loại')),
                ('icon', models.CharField(default='book-open', help_text='Tên Lucide icon hoặc emoji', max_length=50)),
                ('badge_bg', models.CharField(default='bg-amber-100 text-amber-800', max_length=30)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Thể loại sách',
                'verbose_name_plural': 'Thể loại sách',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên phụ huynh')),
                ('child_age', models.CharField(blank=True, max_length=50, verbose_name='Bé mấy tuổi')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Số sao (1-5)')),
                ('comment', models.TextField(verbose_name='Đánh giá về sách và dịch vụ')),
                ('book_bought', models.CharField(blank=True, max_length=200, verbose_name='Cuốn sách đã mua')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Hiển thị trên web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đánh giá của khách',
                'verbose_name_plural': 'Đánh giá của khách',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=30, unique=True, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Họ tên phụ huynh / người nhận')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email nhận thông báo')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Địa chỉ nhận hàng (Số nhà, đường)')),
                ('city', models.CharField(max_length=100, verbose_name='Tỉnh / Thành phố')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú đơn hàng')),
                ('payment_method', models.CharField(choices=[('vietqr', 'Chuyển khoản VietQR tự động'), ('cod', 'Thanh toán tiền mặt khi nhận sách (COD)')], default='vietqr', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('packing', 'Đang gói sách'), ('shipping', 'Đang giao hàng'), ('completed', 'Giao thành công'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=25000, max_digits=10, verbose_name='Phí ship')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền sách')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng thanh toán')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Mã vận đơn bưu cục')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đặt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Quản lý Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Tên ba/mẹ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại / Zalo')),
                ('book_count', models.PositiveIntegerField(default=5, verbose_name='Ước tính số lượng cuốn')),
                ('description', models.TextField(help_text='Vd: Khoảng 20 cuốn truyện tranh Scholastic, Usborne cho bé 5 tuổi, còn mới 90%...', verbose_name='Danh sách hoặc thể loại sách muốn thanh lý/ký gửi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tradein/', verbose_name='Ảnh chụp chồng sách')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ lấy sách (nếu có)')),
                ('status', models.CharField(choices=[('new', 'Mới gửi'), ('contacted', 'Đã liên hệ báo giá'), ('received', 'Đã nhận sách kiểm tra'), ('paid', 'Đã thanh toán / Ký gửi xong'), ('declined', 'Từ chối')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Ghi chú của tiệm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi yêu cầu')),
            ],
            options={
                'verbose_name': 'Yêu cầu ký gửi / Thanh lý sách',
                'verbose_name_plural': 'Ký gửi / Thanh lý sách cũ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên sách (Tiếng Anh)')),
                ('vietnamese_title', models.CharField(blank=True, max_length=255, verbose_name='Tên tiếng Việt / Giới thiệu nhanh')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('author', models.CharField(max_length=200, verbose_name='Tác giả')),
                ('publisher', models.CharField(blank=True, help_text='Usborne, Scholastic, Penguin, Oxford, HarperCollins...', max_length=150, verbose_name='Nhà xuất bản')),
                ('condition_detail', models.CharField(blank=True, help_text='Vd: Gáy chắc chắn, trang giấy đẹp tinh tươm, không ghi chú viết vẽ', max_length=300, verbose_name='Chi tiết thực tế cuốn sách này')),
                ('original_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá bìa gốc (VNĐ)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán thanh lý (VNĐ)')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Số lượng trong kho (Thường là 1)')),
                ('reading_level', models.CharField(blank=True, help_text='Vd: Phonics Stage 2, Lexile 520L, AR 3.4, Grade 3-5...', max_length=100, verbose_name='Trình độ đọc')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số trang')),
                ('cover_type', models.CharField(choices=[('paperback', 'Bìa mềm (Paperback)'), ('hardcover', 'Bìa cứng (Hardcover)'), ('board_book', 'Bìa bồi cứng (Board Book cho bé)'), ('flap_sound', 'Sách tương tác / Lật mở / Âm thanh')], default='paperback', max_length=30, verbose_name='Loại bìa')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm xuất bản')),
                ('series_name', models.CharField(blank=True, max_length=150, verbose_name='Thuộc bộ sách / Series (nếu có)')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='Mã ISBN')),
                ('description', models.TextField(verbose_name='Mô tả & Tóm tắt nội dung cuốn sách')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='Ảnh bìa thực tế')),
                ('extra_image_1', models.ImageField(blank=True, null=True, upload_to='books/extras/', verbose_name='Ảnh mặt sau / gáy')),
                ('extra_image_2', models.ImageField(blank=True, null=True, upload_to='books/extras/', verbose_name='Ảnh trang ruột 1')),
                ('extra_image_3', models.ImageField(blank=True, null=True, upload_to='books/extras/', verbose_name='Ảnh trang ruột 2')),
                ('image_url_fallback', models.URLField(blank=True, max_length=500, verbose_name='Link ảnh ngoài (dự phòng)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sách nổi bật trang chủ')),
                ('is_hot_deal', models.BooleanField(default=False, verbose_name='Giá hời hôm nay')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='store.agegroup', verbose_name='Độ tuổi')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='store.bookcondition', verbose_name='Tình trạng')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='store.category', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Sách tiếng Anh cũ',
                'verbose_name_plural': 'Kho Sách tiếng Anh cũ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='Tên sách lúc đặt')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.book', verbose_name='Sách')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
    ]
