# Generated by Django 6.1.1 on 2026-09-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán tiền mặt khi nhận sách (COD)'), ('vietqr', 'Chuyển khoản (Đơn cũ)')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
